### ISSUE TITLE
Citation style is not resolved in Toctree

### ISSUE THREAD

**Issue by elnikkis** [mcmtroffaes/sphinxcontrib-bibtex#282] opened 2022-02-01 06:17 UTC
I am using :cite: role in the article title. When I include the article by Toctree directive, the citation in the title is not resolved.

Example rst:

```
Article title :cite:`testlabel`
===================================
```

Then, Toctree directive just produces "Article title testlabel" in html.
Is this correct behavior?

I expected the result such as "Article title [XX 20]" with my custom style.

**Comment by mcmtroffaes** [comment] 2022-02-01 08:45
Thanks for reporting, and yes I can reproduce this. I suspect that by the time the toctree is constructed, the fully rendered label isn't know yet, and thus docutils simply uses the bibtex citation key. It would be nice to convince toctree to use the final rendered text... however I'm not sure how to achieve that!

**Comment by mcmtroffaes** [comment] 2022-02-08 10:37
I've documented the problem in the docs. I'm not sure there's much else I can do, I'm afraid: toctree appears to be designed to simply take the reference target... If anyone knows of a way of telling toctree to use some other attribute (ideally not before env-updated time, because then the labels are known), I'd be keen to learn.

**Comment by mcmtroffaes** [comment] 2022-02-19 15:24
Closing since there's nothing more I think I can do about this, as it is a sphinx limitation... If someone has an idea for dealing with this in a better way, I'd love to learn.

**Closed by mcmtroffaes** 2022-02-19 15:24 UTC
