### ISSUE TITLE
Second @manual with same title but different edition not found

### ISSUE THREAD

**Issue by sebhub** [mcmtroffaes/sphinxcontrib-bibtex#173] opened 2019-08-07 04:53 UTC
I have the following bibtex entries:
```
@manual{ABC_R1,
  author       = {xyz},
  title        = {{ABC}},
  edition      = 1,
  year         = {2019},
}
@manual{ABC_R2,
  author       = {xyz},
  title        = {{ABC}},
  edition      = 2,
  year         = {2019},
}
```
In a *.rst file:
```
:cite:`ABC_R1`
:cite:`ABC_R2`
```
This gives the following warnings:
```
*.rst:*: WARNING: citation not found: ABC_R1
```

**Comment by mcmtroffaes** [comment] 2019-09-04 09:19
I've been able to reproduce this, thanks for reporting. It looks like you found a bug in the pybtex sorting code. I'll submit a fix for this upstream in a moment.

**Comment by mcmtroffaes** [comment] 2019-09-04 09:22
See upstream patch here: https://bitbucket.org/pybtex-devs/pybtex/pull-requests/15/ensure-sort-only-sorts-and-that-it-does/diff

**Comment by mcmtroffaes** [comment] 2019-09-09 07:05
The fix has been merged upstream. You can either wait for the next release of pybtex, or install the development version of pybtex with

```bash
pip install git+https://bitbucket.org/pybtex-devs/pybtex
```

Thanks again for reporting!

**Closed by mcmtroffaes** 2019-09-09 07:05 UTC

**Comment by sebhub** [comment] 2019-09-10 05:17
Thanks a lot for fixing this issue. This is really nice.

**Comment by mcmtroffaes** [comment] 2019-09-10 08:09
You're most welcome, glad I could help!
