### ISSUE TITLE
Support for cython files?

### ISSUE THREAD

**Issue by ojeda-e** [mcmtroffaes/sphinxcontrib-bibtex#308] opened 2022-08-17 02:35 UTC
I am currently working on updating docs in the [MDAnalysis](https://www.mdanalysis.org/) organization. I am using the `sphinxcontrib-bibtex` extension to use BibTex citation format in our documentation. Everything works well for our python files. However, I find that the build breaks when introducing BibTex format to `.pyx` files. 

I'm aware that Sphinx offers support for Cython files (https://github.com/sphinx-doc/sphinx/issues/1117), but I can't find any information related to support of Sphinx + BibTex extension in this case. Does the `sphinxcontrib-bibtex` extension support Cython files?

Regardless of the answer, it would be a good idea to add some info on this topic in the README.

**Comment by mcmtroffaes** [comment] 2022-08-17 06:44
Thanks for reporting. I wasn't aware that sphinx supported cython source files, and I'm very glad to learn! Can you share a minimal example that you'd expect to work but doesn't?

**Comment by mcmtroffaes** [comment] 2022-08-25 08:08
@ojeda-e Any progress from your end? You can use the test module that I wrote (and which is now part of the regression tests) as a basis for creating an example that reproduces your problem.

**Comment by mcmtroffaes** [comment] 2022-08-26 14:02
Closing due to non-response for over a week, Cython test added, and all appears to be working from those tests. I still would like to know why the build isn't working (even if it has nothing to do with sphinxcontrib-bibtex). Feel free to reopen if the cause is identified as sphinxcontrib-bibtex, or leave a comment if you figure out the problem was elsewhere.

**Closed by mcmtroffaes** 2022-08-26 14:02 UTC

**Comment by ojeda-e** [comment] 2022-08-28 00:11
Sorry for the delayed answer. This is a project I work on when I have some extra time and last week was pretty busy at my full-time job.
First, thanks for adding the tests. Although I was working on a minimal example, it was a bit more complicated because I wanted to replicate some functionality from MDAnalysis. For example, I wanted to see if there was a conflict when using duecredit, when referencing modules with `sphinx.ext.intersphinx`, among others. In the end, I found out that effectively, references in cython files are not the problem. It works as in other python files. 

I am still trying to figure out what's the root of the problem in our case. What I have identified so far is one single reference that breaks the docs, which happened to be in the Cython file and hence why I opened this issue. Unfortunately, the references in the library are very complex and debugging is not easy. If I identify the problem, I'll share the details here. 

Maybe this is an opportunity to ask you some questions about the usage of the `keyprefix` option.  Since we are using `keyprefix` and `labelprefix` to cite the same reference in different documents (as shown in [sphinxcontrib-bibtex docs](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#key-prefixing)), would you please confirm that I can use a given reference with and with no prefix simultaneously? For example, let's say I want the reference key `Ref1` cited in three different files. In two of them, I use the reference with no prefix, while in the other two I use the prefix. Something like this:

**File 1**
```
"My docstrings cite :cite:p:`Ref1`"
.. bibliography::
   
   Ref1
```

**File 2**
```
"My second docstrings cite :cite:p:`a-Ref1`"
.. bibliography::
   :keyprefix: a-
   :labelprefix: ᵃ
   
   Ref1
```

**File 3**
```
"My third docstrings cite :cite:p:`b-Ref1`"
.. bibliography::
   :keyprefix: b-
   :labelprefix: ᵇ
   
   Ref1
```
Is this supported? Or is the use of prefixes designed in a way that once I use a prefix, anywhere else where I cite I should always use a prefix (a different one)? 
From what I have seen so far, the example above can be used. In this case, there are no errors when building the docs. But I wonder if it is bad usage and if it is intended to be an error, just not being caught properly. 

In our case, the problematic reference is in four different files (including the Cython file). When using a different prefix for each file, a non-sense error says that there is a duplicated reference somewhere else, which is not (double-checked a dozen times). With that said, some of the references use prefixes following the example above. If that is supposed to be an error that is not properly caught, there is a chance that the triggered error is not accurate. But it's just an option and I'm exploring and given the size of the references in the library takes some time.

**Comment by mcmtroffaes** [comment] 2022-08-28 11:36
Many thanks for getting back on this, and for taking the effort to detail your progress.

An empty prefix is treated like any other prefix so yes you should be able to use the scenario you described. If that does not work, then that would be a bug.

Feel free to come back here if you found the problem and especially if it does turn out to be a problem with this extension. Good luck!
