### ISSUE TITLE
Got unresolved references for latex build after successful html build

### ISSUE THREAD

**Issue by skirpichev** [mcmtroffaes/sphinxcontrib-bibtex#226] opened 2020-12-30 13:32 UTC
E.g. [this build](https://pipelines.actions.githubusercontent.com/Mhio7tkdSz9Y1LLE2Og4XLyBoqPmBA3bW1FN7BkseNTYupLrQC/_apis/pipelines/1/runs/2034/signedlogcontent/6?urlExpires=2020-12-30T12%3A10%3A56.9719719Z&urlSigningMethod=HMACV1&urlSignature=QUpJnu4tORUgyWleB6GJHaYLxNET%2B8uzYKqrtE%2FyjeQ%3D) in the [Diofant](https://github.com/diofant/diofant) project.

I was able to reproduce this locally as well (with `python setup.py build_sphinx -W -b html,latex`), which results in
```
Warning, treated as error:
could not find bibtex key Gruntz1996limits
```

**Comment by mcmtroffaes** [comment] 2020-12-30 19:40
Thanks, I have this reproduced.

The problem is that if no targets are up to date, sphinx does not run the consistency check, and therefore the cross-reference data, which is required for the post-transform (and which sphinx does not store in the pickle), is not created... This normally doesn't show up as a problem because the consistency check will run as soon as at least one document is updated. It only happens whey you build different targets as you are. I'll need to check with upstream sphinx if it would be possible to pickle the environment only after the consistency check.

**Comment by mcmtroffaes** [comment] 2020-12-31 09:28
I've posted an upstream patch for this, and I hope it can be accepted. 🤞 For now, you can use this sphinx branch:

https://github.com/mcmtroffaes/sphinx/tree/feature/check-consistency-custom-data

**Comment by mcmtroffaes** [comment] 2020-12-31 20:26
@skirpichev I think I may have found a simpler solution by hooking into a different Sphinx event. Could you try the current develop branch and see if this fixes your problem?

**Comment by skirpichev** [comment] 2021-01-01 05:49
Thank you.  Seems to be working locally.

I've created https://github.com/diofant/diofant/pull/1110 to test this with Github CI.

**Comment by mcmtroffaes** [comment] 2021-01-01 08:19
Great! Thanks for running this through your CI. I've had a look at the output and this is now fixed as far as I can tell. Will do another quick hotfix release.

**Closed by mcmtroffaes** 2021-01-01 08:19 UTC
Labels: bug
