### ISSUE TITLE
Invalid HTML generated

### ISSUE THREAD

**Issue by flying-sheep** [mcmtroffaes/sphinxcontrib-bibtex#329] opened 2023-06-05 15:42 UTC
Older versions of docutilse [have a bug](https://sourceforge.net/p/docutils/patches/195/), where a simple `.. bibliography::` results in this HTML:

```html
<div class="docutils container" id="id1">
<div class="citation" id="id2" role="doc-biblioentry">
<span class="label">...</span>
<p>...</p>
</div>
</div>
</div>
```

note the two opening and three closing div tags.

This can be fixed by depending on `docutils>=0.20`

**Comment by mcmtroffaes** [comment] 2023-06-05 17:03
Thanks for reporting. Duplicate of #309.

**Closed by mcmtroffaes** 2023-06-05 17:03 UTC
