### ISSUE TITLE
Need to run Sphinx twice for references to be found

### ISSUE THREAD

**Issue by jedbrown** [mcmtroffaes/sphinxcontrib-bibtex#215] opened 2020-12-15 01:06 UTC
We just updated to version 2.0 and now get `citation not found` warnings and this instruction:
```
WARNING: bibtex citations changed, rerun sphinx
```
I see this is documented behavior, but it's quite disruptive. This project should at least document the recommended procedure for running sphinx twice as needed on ReadTheDocs or other automated workflows.

**Comment by mcmtroffaes** [comment] 2020-12-15 08:16
Closing as a duplicate of #214, please refer to the discussion there. The documentation does give instructions for running sphinx on services such as RTD. You don't have to run sphinx twice as long as the json file is present.

**Closed by mcmtroffaes** 2020-12-15 08:16 UTC
