### ISSUE TITLE
Figure captions with citations fail in building PDF

### ISSUE THREAD

**Issue by astonzhang** [mcmtroffaes/sphinxcontrib-bibtex#307] opened 2022-08-01 21:10 UTC
### Describe the bug

Figure captions with citations fail in building PDF. Here is an example (note that `:citet:` is an alias of `:cite:t:`):

Input ipynb:
![Screen Shot 2022-08-01 at 11 59 48 AM](https://user-images.githubusercontent.com/22279212/182223966-66be83bb-cde5-44e4-82e4-4fc17f812ae6.png)

Output tex:
![bad](https://user-images.githubusercontent.com/22279212/182225049-62aa7654-3310-4508-bbd8-e79ce74eb331.png)

When compiling PDF from this tex, the following error shows up:

![Screen Shot 2022-08-01 at 11 56 21 AM](https://user-images.githubusercontent.com/22279212/182225235-fc2269b9-e96e-43dc-ba8c-eba55f947ec8.png)

### How to Reproduce

```
$ git clone -b sphinx-latex https://github.com/d2l-ai/d2l-en.git
$ cd d2l-en
$ vi static/post_latex/main.py # Comment out my hack https://github.com/d2l-ai/d2l-en/blob/sphinx-latex/static/post_latex/main.py#L141
$ pip install d2lbook
$ d2lbook build pdf  # The output pdf should be at _build/pdf
```

### Expected behavior

As a hack for this issue, I [post-process this tex file](https://github.com/d2l-ai/d2l-en/blob/master/static/post_latex/main.py#L136). So the processed tex has a `\protect` and becomes:
![good](https://user-images.githubusercontent.com/22279212/182225755-422b3986-5860-4494-99aa-6a65fd817e3c.png)

Then the output PDF is:
![Screen Shot 2022-08-01 at 11 56 32 AM](https://user-images.githubusercontent.com/22279212/182225972-426b503b-901d-4b36-b8f1-652328d1fbcb.png)

### Your project

https://github.com/d2l-ai/d2l-en/ and https://github.com/d2l-ai/d2l-book

### OS

Linux

### Python version

3.8

### Sphinx version

5.1.1

**Comment by mcmtroffaes** [comment] 2022-08-10 06:38
Thanks for the detailed report, and apologies for the late reply - I've been on vacation. Using ``\protect`` is indeed the correct solution, and it would be possible to patch sphinxcontrib-bibtex so it always outputs ``\protect\hyperlink{...}``. However I'm wary of any implications of using ``\protect`` everywhere for these hyperlinks - I don't understand enough about the robust/fragile system to know whether or not it will break something.

I'll close this as a duplicate of #276 - there you can find one idea for a solution (using the etoolbox package), but so far it doesn't work. Feel free to chime in there if you have further ideas.

**Closed by mcmtroffaes** 2022-08-10 06:38 UTC
